# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  build:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run: npm i
      - save_cache:
          paths:
            - "npm-packages"
          key: "/src/node_modules"
      - run:
          name: Run lint
          command: npm run lint
  test:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i
      - run: npm run test

  analyze:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run: npm i
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm audit

workflows:
  sample: 
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test